import json

import ollama


MODEL_NAME = "llama3.2:3b"

# Ollama 0.6.2 accepts the timeout through the client,
# not through Client.chat().
OLLAMA_CLIENT = ollama.Client(
    timeout=120.0
)


def format_metadata_for_prompt(
    metadata: dict,
) -> str:
    """
    Format deposition metadata for inclusion in an LLM prompt.

    Each metadata field preserves:
    - value
    - source
    - extraction confidence
    """
    if not metadata:
        return (
            "No deposition metadata was available."
        )

    lines = []

    for field, value in metadata.items():
        if isinstance(value, dict):
            field_value = value.get(
                "value",
                None,
            )
            source = value.get(
                "source",
                "",
            )
            confidence = value.get(
                "confidence",
                0.0,
            )

            lines.append(
                f"{field}: value={field_value!r}; "
                f"source={source!r}; "
                f"confidence={confidence}"
            )
        else:
            lines.append(
                f"{field}: {value!r}"
            )

    return "\n".join(lines)


def classify_chunk(
    chunk: list[dict],
    metadata: dict,
) -> dict:
    """
    Classify one transcript chunk into a topic.

    The model receives the transcript together with explicitly
    extracted deposition metadata.

    Page and line provenance are not generated by the model.
    They are taken deterministically from the transcript records.
    """
    transcript = "\n".join(
        (
            f"[Page {record['page']}, "
            f"Line {record['line']}] "
            f"{record['text']}"
        )
        for record in chunk
    )

    prompt = f"""
You are analyzing a legal deposition transcript.

Identify the main topic discussed in this transcript segment.

Return JSON only:

{{
  "topic": "short specific topic title",
  "summary": "short factual summary",
  "evidence": "verbatim contiguous excerpt copied exactly from the transcript"
}}

Rules:
- The topic must describe what is actually discussed in this transcript segment.
- Do not invent facts.
- Do not make the topic broader than the transcript supports.
- Do not make legal conclusions that the witness does not establish.
- If the witness expresses uncertainty or lack of knowledge, preserve that limitation.
- Evidence MUST be copied verbatim from the transcript.
- Evidence MUST be a contiguous excerpt from the transcript.
- Do NOT paraphrase the evidence.
- Do NOT summarize the evidence.
- Do NOT combine separate sentences from different parts of the transcript.
- Preserve the original wording of the transcript in the evidence.
- Do not add words that are not present in the transcript.
- Do not remove words from the selected excerpt except for surrounding whitespace.
- Select a short excerpt that directly supports the proposed topic.
- If several statements support the topic, choose the shortest sufficient contiguous excerpt.
- Do not include page or line numbers inside the evidence.
- Do not invent page or line numbers.

DEPOSITION METADATA:
{format_metadata_for_prompt(metadata)}

TRANSCRIPT:
{transcript}
"""

    response = OLLAMA_CLIENT.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        format="json",
        options={
            "temperature": 0,
        },
    )

    data = json.loads(
        response["message"]["content"]
    )

    return {
        "topic": str(
            data.get(
                "topic",
                "",
            )
        ).strip(),
        "summary": str(
            data.get(
                "summary",
                "",
            )
        ).strip(),
        "evidence": str(
            data.get(
                "evidence",
                "",
            )
        ).strip(),
    }


def verify_topic_semantics(
    chunk: list[dict],
    topic: str,
    summary: str,
) -> dict:
    """
    Independently verify whether the proposed topic accurately
    describes the transcript segment.

    The verifier separately evaluates:
    - transcript support
    - topic relevance
    - topic specificity

    It also provides an overall semantic_supported decision
    and semantic_score.

    This validation is intentionally independent from the
    deterministic transcript/evidence validation.
    """
    transcript = "\n".join(
        (
            f"[Page {record['page']}, "
            f"Line {record['line']}] "
            f"{record['text']}"
        )
        for record in chunk
    )

    prompt = f"""
You are independently reviewing a proposed topic for a
legal deposition transcript.

Determine whether the proposed topic is an accurate description
of what the transcript segment discusses or establishes.

The topic does NOT need to reproduce every detail of the
transcript. It should accurately represent the main subject
without adding unsupported factual or legal conclusions.

Return JSON only:

{{
  "transcript_supported": true or false,
  "topic_relevant": true or false,
  "topic_specific": true or false,
  "semantic_supported": true or false,
  "semantic_score": 0,
  "semantic_reason": "short explanation"
}}

Definitions:

1. transcript_supported

True when the transcript directly discusses or provides
meaningful support for the subject represented by the topic.

A topic can still be transcript-supported when the witness:
- expresses uncertainty,
- says they do not remember,
- says information is unavailable,
- discusses the absence of a finding,
- discusses an investigation without establishing its result.

Do NOT turn an uncertain statement into a factual finding.

2. topic_relevant

True when the proposed topic materially represents the
subject discussed in the transcript.

Do not require every word of the topic to appear verbatim.

3. topic_specific

True when the topic is specific enough to identify the
discussion without making a broader or stronger claim than
the transcript supports.

A topic should be marked false only when it materially
overgeneralizes the transcript or adds an unsupported claim.

4. semantic_supported

Give an overall independent judgment.

Set this to true when the proposed topic is an accurate,
transcript-grounded description of the discussion.

It is acceptable for a topic to describe:
- an investigation,
- a witness's lack of knowledge,
- an allegation,
- a question about enforceability,
- missing documentation,
- a regulatory issue,

provided the topic does not falsely state that the underlying
claim was established.

5. semantic_score

Give a score from 0 to 100 based on how accurately the proposed
topic represents the transcript.

Use approximately:
- 90-100: very strong and precise support
- 80-89: strong support with minor generalization
- 70-79: adequate support; topic is usable
- 50-69: partial or questionable support
- below 50: weak or unsupported

Important rules:

- Do not treat mere word similarity as sufficient support.
- Do not assume that a related subject proves a specific claim.
- Do not convert uncertainty into a factual finding.
- If the witness says they do not remember something, the topic
  may describe the discussion of that issue, but must not claim
  that the underlying fact was established.
- Distinguish "an investigation existed" from
  "the investigation found X".
- Distinguish "the witness discussed enforceability" from
  "the loans were legally enforceable".
- Distinguish "there were questions about documents" from
  "the documents were definitively invalid".
- Do not reject a topic merely because it summarizes a group
  of related statements rather than one exact sentence.
- Do not require exact lexical matching between the topic and
  transcript.
- Be conservative about factual claims, but do not reject an
  accurately summarized discussion merely because the witness
  expressed uncertainty.
- The final semantic_supported decision should reflect the
  overall accuracy of the proposed topic.

PROPOSED TOPIC:
{topic}

PROPOSED SUMMARY:
{summary}

TRANSCRIPT:
{transcript}
"""

    response = OLLAMA_CLIENT.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        format="json",
        options={
            "temperature": 0,
        },
    )

    data = json.loads(
        response["message"]["content"]
    )

    def as_bool(
        value,
    ) -> bool:
        if isinstance(value, bool):
            return value

        if isinstance(value, str):
            return value.strip().lower() in {
                "true",
                "yes",
                "1",
            }

        return bool(value)

    transcript_supported = as_bool(
        data.get(
            "transcript_supported",
            False,
        )
    )

    topic_relevant = as_bool(
        data.get(
            "topic_relevant",
            False,
        )
    )

    topic_specific = as_bool(
        data.get(
            "topic_specific",
            False,
        )
    )

    semantic_supported = as_bool(
        data.get(
            "semantic_supported",
            False,
        )
    )

    try:
        semantic_score = int(
            data.get(
                "semantic_score",
                0,
            )
        )
    except (
        TypeError,
        ValueError,
    ):
        semantic_score = 0

    semantic_score = max(
        0,
        min(
            100,
            semantic_score,
        ),
    )

    semantic_reason = str(
        data.get(
            "semantic_reason",
            "",
        )
    ).strip()

    return {
        "semantic_supported": semantic_supported,
        "transcript_supported": transcript_supported,
        "topic_relevant": topic_relevant,
        "topic_specific": topic_specific,
        "semantic_score": semantic_score,
        "semantic_reason": semantic_reason,
    }


def verify_topic_transcript_support(
    chunk: list[dict],
    topic: str,
    evidence: str,
) -> dict:
    """
    Deterministically verify that:

    1. evidence is grounded in the transcript,
    2. the evidence contains meaningful words from the topic.

    This check is independent of the LLM semantic verifier.
    """
    evidence = str(
        evidence or ""
    ).strip()

    topic = str(
        topic or ""
    ).strip()

    if not evidence:
        return {
            "supported": False,
            "reason": (
                "No evidence was provided."
            ),
        }

    if not topic:
        return {
            "supported": False,
            "reason": (
                "No topic was provided."
            ),
        }

    def normalize(
        text: str,
    ) -> str:
        return " ".join(
            text.lower().split()
        )

    def meaningful_words(
        text: str,
    ) -> set[str]:
        return {
            word.strip(
                ".,:;!?()[]{}\"'-"
            ).lower()
            for word in text.split()
            if len(
                word.strip(
                    ".,:;!?()[]{}\"'-"
                )
            ) >= 4
        }

    transcript_text = " ".join(
        record["text"]
        for record in chunk
    )

    normalized_transcript = normalize(
        transcript_text
    )

    normalized_evidence = normalize(
        evidence
    )

    if normalized_evidence in normalized_transcript:
        evidence_grounded = True
    else:
        evidence_words = meaningful_words(
            normalized_evidence
        )

        transcript_words = meaningful_words(
            normalized_transcript
        )

        if not evidence_words:
            return {
                "supported": False,
                "reason": (
                    "Evidence does not contain enough "
                    "meaningful words for deterministic "
                    "verification."
                ),
            }

        evidence_overlap = (
            evidence_words
            & transcript_words
        )

        overlap_ratio = (
            len(evidence_overlap)
            / len(evidence_words)
        )

        if overlap_ratio < 0.60:
            return {
                "supported": False,
                "reason": (
                    "Evidence is not sufficiently "
                    "grounded in the transcript."
                ),
            }

        evidence_grounded = True

    topic_words = meaningful_words(
        topic
    )

    evidence_words = meaningful_words(
        evidence
    )

    if not topic_words:
        return {
            "supported": False,
            "reason": (
                "Topic does not contain enough "
                "meaningful words."
            ),
        }

    topic_overlap = (
        topic_words
        & evidence_words
    )

    topic_overlap_ratio = (
        len(topic_overlap)
        / len(topic_words)
    )

    if not topic_overlap:
        return {
            "supported": False,
            "reason": (
                "Topic has no meaningful lexical "
                "overlap with the supporting evidence."
            ),
        }

    if topic_overlap_ratio < 0.50:
        return {
            "supported": False,
            "reason": (
                "Supporting evidence does not contain "
                "enough of the topic's meaningful terms."
            ),
        }

    return {
        "supported": True,
        "reason": (
            "Evidence is grounded in the transcript "
            "and contains meaningful support for the topic."
        ),
    }


def combine_semantic_validation(
    deterministic_support: dict,
    semantic_result: dict,
) -> dict:
    """
    Combine deterministic transcript support and independent
    semantic validation using a fail-closed decision.

    Deterministic transcript support remains mandatory.

    The semantic verifier provides an independent overall
    semantic judgment. Its individual dimensions are retained
    as diagnostic information rather than making every dimension
    a separate hard gate.

    A topic is supported only when:
    - deterministic transcript support passes,
    - semantic_supported is true,
    - semantic score is at least 70.
    """
    deterministic_supported = bool(
        deterministic_support.get(
            "supported",
            False,
        )
    )

    semantic_supported = bool(
        semantic_result.get(
            "semantic_supported",
            False,
        )
    )

    try:
        semantic_score = int(
            semantic_result.get(
                "semantic_score",
                0,
            )
        )
    except (
        TypeError,
        ValueError,
    ):
        semantic_score = 0

    semantic_score = max(
        0,
        min(
            100,
            semantic_score,
        ),
    )

    if not deterministic_supported:
        return {
            "status": "REVIEW",
            "supported": False,
            "reason": (
                "Deterministic transcript support failed."
            ),
        }

    if not semantic_supported:
        return {
            "status": "REVIEW",
            "supported": False,
            "reason": (
                "Semantic verifier did not confirm "
                "transcript support."
            ),
        }

    if semantic_score < 70:
        return {
            "status": "REVIEW",
            "supported": False,
            "reason": (
                "Independent semantic score is below "
                "the 70-point acceptance threshold."
            ),
        }

    return {
        "status": "SUPPORTED",
        "supported": True,
        "reason": (
            "Deterministic transcript support and "
            "independent semantic validation passed."
        ),
    }