import json

import ollama


MODEL_NAME = "llama3.2:3b"


def get_fallback_evidence(chunk: list[dict]) -> str:
    """
    Return a short piece of actual transcript text.

    Evidence is always selected directly from the transcript
    rather than generated by the LLM.
    """

    # Prefer witness answers because they usually provide
    # substantive evidence for the identified topic.
    for record in chunk:
        text = record["text"].strip()

        if text.startswith("THE WITNESS:"):
            return text

    # Prefer answer lines beginning with A.
    for record in chunk:
        text = record["text"].strip()

        if text.startswith("A    "):
            return text

    # Final fallback: first non-empty transcript line.
    for record in chunk:
        text = record["text"].strip()

        if text:
            return text

    return ""


def classify_chunk(chunk: list[dict]) -> dict:
    """
    Ask the local LLM to identify the main topic.

    Evidence is deliberately NOT generated by the LLM.
    It is selected directly from the supplied transcript chunk
    to guarantee provenance.
    """

    transcript_text = "\n".join(
        f"[Page {record['page']}, Line {record['line']}] {record['text']}"
        for record in chunk
    )

    prompt = f"""
You are analyzing a legal deposition transcript.

Identify the MAIN topic discussed in the transcript segment below.

Return ONLY valid JSON using exactly this structure:

{{
  "topic": "short descriptive topic name",
  "summary": "one sentence explaining what is discussed"
}}

Rules:

1. Use ONLY information present in the transcript.
2. Do NOT invent facts.
3. Do NOT provide evidence.
4. Do NOT include page numbers or line numbers.
5. Keep the topic concise and descriptive.
6. Return ONLY JSON.

TRANSCRIPT SEGMENT:

{transcript_text}
"""

    response = ollama.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        format="json",
        options={
            "temperature": 0,
        },
    )

    result = json.loads(
        response["message"]["content"]
    )

    result["topic"] = str(
        result.get("topic", "Unclassified topic")
    ).strip()

    result["summary"] = str(
        result.get("summary", "")
    ).strip()

    # Evidence is selected directly from the source chunk.
    result["evidence"] = get_fallback_evidence(chunk)

    return result