import json

import ollama


MODEL_NAME = "llama3.2:3b"


def get_fallback_evidence(
    chunk: list[dict],
    topic: str = "",
) -> str:
    """
    Select the most relevant supporting evidence directly
    from the transcript.

    Evidence is never generated by the LLM.
    The selector uses deterministic topic-word matching
    plus simple quality penalties.
    """
    filler = {
        "yes.",
        "no.",
        "okay.",
        "ok.",
        "yeah.",
        "sorry.",
        "i'm sorry.",
        "thank you.",
        "correct.",
        "right.",
        "i understand.",
        "i have not.",
    }

    stop_words = {
        "the",
        "and",
        "for",
        "with",
        "from",
        "into",
        "about",
        "their",
        "they",
        "them",
        "that",
        "this",
        "its",
        "are",
        "was",
        "were",
        "has",
        "have",
        "had",
        "not",
        "but",
        "you",
        "your",
        "loan",
        "loans",
        "student",
        "students",
    }

    # Extract useful words from the generated topic.
    topic_words = {
        word.lower().strip(".,'\"()-")
        for word in topic.split()
        if len(word.strip(".,'\"()-")) >= 4
        and word.lower().strip(".,'\"()-") not in stop_words
    }

    candidates = []

    for record in chunk:
        text = record["text"].strip()

        if not text:
            continue

        normalized = text.lower().strip()

        # Ignore obvious filler responses.
        if normalized in filler:
            continue

        # Ignore extremely short lines.
        if len(text) < 35:
            continue

        score = 0

        # Prefer substantive answer lines.
        if text.startswith("A    "):
            score += 3
        elif text.startswith("THE WITNESS:"):
            score += 2

        # Reward overlap between topic words
        # and words appearing in the transcript line.
        text_words = {
            word.strip(".,:;!?()[]{}\"'-").lower()
            for word in text.split()
        }

        overlap = topic_words & text_words
        score += min(len(overlap) * 3, 12)

        # Penalize lines that are unlikely to be useful
        # as supporting evidence.
        penalty_phrases = [
            "can you rephrase",
            "i'm sorry",
            "i am sorry",
            "outside the scope",
            "i don't remember",
            "i do not remember",
            "let me not answer",
        ]

        for phrase in penalty_phrases:
            if phrase in normalized:
                score -= 5

        # Prefer reasonably informative lines.
        if len(text) >= 80:
            score += 2

        if len(text) >= 140:
            score += 1

        candidates.append(
            (
                score,
                len(overlap),
                len(text),
                text,
            )
        )

    if candidates:
        candidates.sort(
            key=lambda item: (
                item[0],
                item[1],
                item[2],
            ),
            reverse=True,
        )

        return candidates[0][3]

    # Final fallback: first non-empty transcript line.
    for record in chunk:
        text = record["text"].strip()

        if text:
            return text

    return ""


def verify_supporting_quote(
    chunk: list[dict],
    quote: str,
) -> bool:
    """
    Verify that a supporting quote occurs in the
    original transcript chunk.
    """
    if not quote.strip():
        return False

    transcript_text = "\n".join(
        record["text"]
        for record in chunk
    )

    return quote.strip() in transcript_text


def classify_chunk(
    chunk: list[dict],
    metadata: dict | None = None,
) -> dict:
    """
    Ask the local LLM to identify the main topic.

    Optional deposition metadata provides additional
    semantic context to the classifier.

    Evidence is NOT generated by the LLM.
    It is selected directly from the supplied transcript
    to guarantee provenance.
    """
    transcript_text = "\n".join(
        f"[Page {record['page']}, Line {record['line']}] "
        f"{record['text']}"
        for record in chunk
    )

    metadata_context = ""

    if metadata:
        metadata_context = f"""
DEPOSITION METADATA:

Witness:
{metadata.get("witness") or "Not available"}

Case/Matter:
{metadata.get("case_matter") or "Not available"}

Examining Attorney:
{metadata.get("examining_attorney") or "Not available"}

Deposition Date:
{metadata.get("deposition_date") or "Not available"}

Administrative Information Redacted:
{metadata.get("administrative_information_redacted", False)}

Use this metadata only as contextual information.
Do not treat unavailable or redacted fields as facts.
Do not invent any metadata.
"""

    prompt = f"""
You are analyzing a legal deposition transcript.

Identify the MAIN topic discussed in the transcript segment below.

{metadata_context}

Return ONLY valid JSON using exactly this structure:

{{
  "topic": "short descriptive topic name",
  "summary": "one sentence explaining what is discussed"
}}

Rules:

1. Use ONLY information present in the transcript.

2. Do NOT invent facts.

3. Do NOT provide evidence.

4. Do NOT include page numbers or line numbers.

5. Keep the topic concise, specific, and descriptive.

6. Identify the specific subject being discussed, not merely
   the broader category it belongs to.

7. Prefer the actual entity, issue, action, investigation,
   dispute, document, or legal question being discussed.

8. Avoid vague umbrella topics such as:
   "Student Loans", "PEAKS Loans", "Investigations",
   "Expert Testimony", or "Servicing" when the transcript
   provides a more specific subject.

9. The topic should be understandable without reading
   the surrounding chunks.

10. Do not add details that are not supported by the transcript.

11. Metadata may provide contextual information, but the
    generated topic must still be supported by the transcript.

12. Return ONLY JSON.

TRANSCRIPT SEGMENT:

{transcript_text}
"""

    response = ollama.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        format="json",
        options={
            "temperature": 0,
        },
    )

    result = json.loads(
        response["message"]["content"]
    )

    result["topic"] = str(
        result.get(
            "topic",
            "Unclassified topic",
        )
    ).strip()

    result["summary"] = str(
        result.get(
            "summary",
            "",
        )
    ).strip()

    # Evidence is selected directly from the source chunk
    # using the generated topic for deterministic relevance
    # scoring.
    result["evidence"] = get_fallback_evidence(
        chunk,
        result["topic"],
    )

    return result


def verify_topic_semantics(
    chunk: list[dict],
    topic: str,
    summary: str,
) -> dict:
    """
    Independently evaluate whether the generated topic is
    actually supported by the transcript chunk.

    The verifier evaluates semantic relevance only.
    Source provenance is handled separately by Python.
    """
    transcript_text = "\n".join(
        record["text"]
        for record in chunk
    )

    prompt = f"""
You are a strict evaluator checking a topic label generated
from a legal deposition transcript.

TOPIC:

{topic}

SUMMARY:

{summary}

TRANSCRIPT SEGMENT:

{transcript_text}

Determine whether the topic accurately describes the
MAIN subject of this transcript segment.

Return ONLY valid JSON using exactly this structure:

{{
  "semantic_supported": true,
  "semantic_score": 85,
  "semantic_reason": "The transcript primarily discusses..."
}}

Rules:

1. Evaluate the topic against the ENTIRE transcript segment.

2. The topic must describe the main subject actually discussed.

3. Do not accept a topic merely because one word appears
   in the transcript.

4. Do not introduce information that is absent from the transcript.

5. semantic_score must be an integer from 0 to 100.

6. Use these guidelines:

   - 90-100: clearly and directly supported.
   - 70-89: substantially supported but somewhat broad.
   - 50-69: partially or ambiguously supported.
   - 0-49: poorly supported or unrelated.

7. Set semantic_supported to true when the topic is
   substantially supported by the transcript.

8. Explain the decision briefly in semantic_reason.

9. Do NOT provide a quote.

10. Do NOT provide page numbers or line numbers.

11. Return ONLY JSON.
"""

    response = ollama.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        format="json",
        options={
            "temperature": 0,
        },
    )

    result = json.loads(
        response["message"]["content"]
    )

    # Normalize semantic_supported.
    supported = result.get(
        "semantic_supported",
        False,
    )

    if isinstance(supported, str):
        supported = supported.lower() == "true"

    result["semantic_supported"] = bool(
        supported
    )

    # Normalize semantic_score.
    try:
        score = int(
            result.get(
                "semantic_score",
                0,
            )
        )
    except (TypeError, ValueError):
        score = 0

    result["semantic_score"] = max(
        0,
        min(100, score),
    )

    # Normalize semantic_reason.
    result["semantic_reason"] = str(
        result.get(
            "semantic_reason",
            "",
        )
    ).strip()

    return result